version: '3.9'

services:
  db:
    image: postgres
    ports:
      - '4444:5432'
    container_name: 'postgres'
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fitness-api-db

#What is the point of doing this?
volumes:
  db:
    driver: local

networks:
  proxy:
    driver: bridge
    name: proxy
