version: '3.9'

services:
  db:
    image: postgres
    ports:
      - '4444:5432'
    container_name: 'postgres'
    restart: unless-stopped
    # volumes:
    #   - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fitness-api-db
    networks:
      - proxy

  test-db-service:
    image: postgres
    ports:
      - '5555:5432'
    container_name: 'test-postgres-container'
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fitness-api-db
    networks:
      - proxy

  # dev:
  #   container_name: nestjs_api_dev
  #   image: nestjs-api-dev:1.0.0
  #   command: nest start --watch --debug
  #   build:
  #     context: .
  #     target: development
  #     dockerfile: ./Dockerfile
  #   depends_on:
  #     - db
  #   ports:
  #     - 3000:3000
  #   networks:
  #     - nestjs-network

volumes:
  db:

networks:
  # nestjs-network:
  #   driver: bridge
  #   name: nestjs-network
  proxy:
    driver: bridge
    name: proxy
