name: Continuous Integration
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, closed]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
      - run: npm ci
      - run: npm run start:bad
  # deploy: ## <-- this is the new stuff
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: akhileshns/heroku-deploy@v3.12.12
  #     with:
  #       heroku_api_key: ${{secrets.HEROKU_API_KEY}}
  #       heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
  #       heroku_email: ${{secrets.HEROKU_EMAIL}}
  #       remote_branch: master
