name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
  push:
    branches:
      - main
  workflow_dispatch

jobs:
  dev-deploy:
    name: Dev-Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - name: Clean Install
        run: npm ci --legacy-peer-deps
      - name: Start Api
        run: npm run start:bad
