name: Plain-Workflow-Name

on:
  push:
    branches:
      - main

jobs:
  dev-deploy:
    name: Dev-Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      # Linting Too Strict - Removed
      # - name: Linting check
      #   run: npm run lint
      - name: Building application
        run: npm run build
      - name: Build Success
        run: echo App built successfully.
